apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  labels:
    app: mysql-service
  name: mysql-service
spec:
  externalName: versus21c.c7pmwjifbb9j.REG.rds.amazonaws.com
  selector:
    app: mysql-service
  type: ExternalName
status:
  loadBalancer: {}

# Commands 
# k exec -it api-deployment-7f4c89f5d8-98shh -n main -- sh
# nc mysql-service 3306 