apiVersion: v1
kind: Secret
metadata:
  namespace: NAMESPACE
  creationTimestamp: null
  name: credentials
data:
  database: dmVyc3VzMjFj
  host: dmVyc3VzMjFjLmM3cG13amlmYmI5ai5SRUcucmRzLmFtYXpvbmF3cy5jb20=
  password: cGFzc3dvcmQ=
  port: MzMwNg==
  user: YWRtaW4=