apiVersion: v1
kind: Pod
metadata:
spec:
  containers:
  - name: jenkins-slave
    image: alexkdevops/jenkins-slave
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_HOST
      value: 'tcp://localhost:2375'
  - name: dind-daemon
    image: 'docker:18-dind'
    command:
    - dockerd-entrypoint.sh
    tty: true
    securityContext:
      privileged: true   