apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-svc
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: front.alexkdevops.click
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service: 
            name: frontend
            port:
              number: 80
                          
---
apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: frontend
spec: 
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: NAMESPACE
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-pod
        image: ACCT.dkr.ecr.REG.amazonaws.com/REPO:VER
        ports:
        - containerPort: 80       